config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Defines the root path route ("/")
  root 'main#index'
  resources :pokemons, only: %i[index show], path: 'pokedex'
  resources :adoptable_pokemons, only: %i[index show], path: 'pokemons' do
    member do
      get '/adopt', to: 'adoptions#new'
      post '/adopt', to: 'adoptions#create'
      get '/adopt/success', to: 'adoptions#success', as: :success
    end
  end
  resources :faq, only: %i[index]
  # get '/pokemons/adopt/:id', to: 'adoptable_pokemons#adopt', as: 'adopt'
end

app/models/adoptable_pokemon.rb
class AdoptablePokemon < ApplicationRecord
  belongs_to :shelter
  belongs_to :species, class_name: 'Pokemon'
  has_many :adoption

  def age
    return 'Young' unless @birth_date

    today = Date.today
    birth_date_obj = Date.parse(@birth_date)

    age_years = today.year - birth_date_obj.year
    age_years -= 1 if today < birth_date_obj + age_years.years

    young_threshold = 5
    adult_threshold = 10

    if age_years < young_threshold
      'Young'
    elsif age_years < adult_threshold
      'Adult'
    else
      'Mature'
    end
  end

  def health
    case health_status
    when 'special_diet'
      'Requires special diet'
    else
      'Healthy'
    end
  end

  def is_during_adoption
    adoption.first&.pending
  end
end

app/models/adoption.rb
class Adoption < ApplicationRecord
  enum city: {
    pallet_town: 'pallet_town',
    viridian_city: 'viridian_city',
    pewter_city: 'pewter_city',
    cerulean_city: 'cerulean_city',
    vermilion_city: 'vermilion_city',
    lavender_town: 'lavender_town',
    celadon_city: 'celadon_city',
    fuchsia_city: 'fuchsia_city',
    saffron_city: 'saffron_city',
    cinnabar_island: 'cinnabar_island'
  }

  enum household_ownership: {
    rent: 'rent',
    own: 'own'
  }

  belongs_to :adoptable_pokemon

  validates :adoptable_pokemon, presence: true
  validates :full_name, presence: true
  validates :email_address, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone_number, presence: true,
                           format: { with: /\A\+?[\d\s\-()]{7,15}\z/, message: 'should be a valid phone number' }
  validates :city, presence: true, inclusion: { in: cities.keys }
  validates :household_ownership, presence: true, inclusion: { in: household_ownerships.keys }
  validates :household_size, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :household_children, presence: true
  validates :has_experience, inclusion: { in: [true, false] }
  validates :why_adopt_pokemon, presence: true
  validates :desired_pokemon_traits, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/evolution.rb
class Evolution < ApplicationRecord
  has_many :pokemon_evolutions
  belongs_to :item, optional: true
  belongs_to :pokemon, class_name: 'Pokemon', optional: true
  belongs_to :evolution_pokemon, class_name: 'Pokemon', optional: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :evolution

  def image
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/#{name.downcase.gsub(' ', '-')}.png"
  end
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokemon_evolutions
  has_many :adoptable_pokemons
  belongs_to :evolution, optional: true

  def color
    main_type = types.first&.downcase&.to_sym
    POKEMON_TYPE_COLORS[main_type] || '#83A498' # Defaults to accent color if no color is found
  end

  def image
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/#{id}.png"
  end

  default_scope { order(id: :asc) }
end

app/models/pokemon_evolution.rb
class PokemonEvolution < ApplicationRecord
  belongs_to :pokemon
  belongs_to :evolution
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  has_many :adoptable_pokemon
end

app/controllers/adoptable_pokemons_controller.rb
class AdoptablePokemonsController < ApplicationController
  def index
    search = params[:q]
    page = params[:page] || 1

    @adoptable_pokemons = AdoptablePokemon.joins(:species).all
    if search.present?
      @adoptable_pokemons = @adoptable_pokemons.where('lower(adoptable_pokemons.name) LIKE ? OR lower(pokemons.name) LIKE ?',
                                                      "%#{search.downcase}%", "%#{search.downcase}%")
    end
    @adoptable_pokemons = @adoptable_pokemons.paginate(page:, per_page: 16)
  end

  def show
    @adoptable_pokemon = AdoptablePokemon.find(params[:id])
    @species = @adoptable_pokemon.species
  end
end

private

def search_params
  params.permit(:q)
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  before_action :check_if_adoptable, only: %i[new create]

  def new
    @adoption = Adoption.new
    @adoptable_pokemon = AdoptablePokemon.find(params[:id])
  end

  def create
    @adoption = Adoption.new(adoption_params)
    @adoptable_pokemon = AdoptablePokemon.find(params[:id])

    if @adoption.save
      redirect_to success_adoptable_pokemon_path(params[:id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  def success
    @adoptable_pokemon = AdoptablePokemon.find(params[:id])
  end

  private

  def check_if_adoptable
    @adoption = Adoption.find_by(adoptable_pokemon: params[:id])

    return unless @adoption&.pending

    raise ActionController::RoutingError, 'Not Found'
  end

  def adoption_params
    params.require(:adoption).permit(:adoptable_pokemon_id, :full_name, :email_address, :phone_number, :city, :household_ownership,
                                     :household_size, :household_children, :has_experience, :why_adopt_pokemon, :desired_pokemon_traits)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ActionView::Base.default_form_builder = FormBuilders::TailwindFormBuilder
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @pokemon_count = Pokemon.count
    @recent_adoptable_pokemons = AdoptablePokemon.last(6).reverse
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    search = params[:q]
    page = params[:page] || 1

    @pokemons = Pokemon.all
    @pokemons = @pokemons.where('lower(name) LIKE ?', "%#{search.downcase}%") if search.present?
    @pokemons = @pokemons.paginate(page:, per_page: 32)
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @evolutions = @pokemon.pokemon_evolutions.map(&:evolution)

    page = params[:page] || 1
    @adoptable_pokemons = AdoptablePokemon.where('species_id = ?', params[:id])
    @adoptable_pokemons = @adoptable_pokemons.paginate(page:, per_page: 16)
  end
end

private

def search_params
  params.permit(:q)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/views/adoptable_pokemons/_adoptable_pokemon.html.erb
<%= link_to adoptable_pokemon, data: { turbo_frame: "_top" } do %>
  <article class="relative grid grid-cols-[auto_1fr] grid-rows-[auto_auto] lg:flex gap-x-6 lg:gap-x-11 lg:h-36 rounded-2xl text-zinc-100 lg:items-center pt-6 lg:pt-0 px-8 hover:brightness-90 overflow-hidden" style="background-color: <%= adoptable_pokemon.species.color %>">
    <%= image_tag("pokeball.svg", class: "absolute -right-4 -bottom-4 h-32 opacity-25 -rotate-45", alt: "a pokeball") %>
    <section>
      <% if adoptable_pokemon.is_during_adoption %>
        <li class="px-4 py-1 text-xs w-fit bg-zinc-900 bg-opacity-25 rounded-2xl font-semibold">
          During Adoption
        </li>
      <% end %>
      <span class="block mt-1 text-3xl lg:text-6xl font-semibold opacity-25">#<%= adoptable_pokemon.species.id.to_s.rjust(3, '0') %></span>
      <h4 class="text-lg font-semibold"><%= adoptable_pokemon.species.name %></h4>
    </section>
    <section class="flex flex-col gap-y-1 row-span-2">
      <ul class="flex gap-x-2">
        <% adoptable_pokemon.species.types.each do |type| %>
          <li class="px-4 py-1 text-sm bg-zinc-100 bg-opacity-25 rounded-2xl font-semibold">
            <%= type %>
          </li>
        <% end %>
      </ul>
      <h3 class="text-2xl lg:text-4xl font-semibold mt-1 lg:mt-0"><%= adoptable_pokemon.name %></h3>
      <span class="font-semibold"><%= adoptable_pokemon.shelter.name %> Shelter</span>
    </section>
    <table class="hidden lg:block">
      <tr>
        <th class="text-end text-zinc-200 font-semibold pr-3">Age</th>
        <td class="font-semibold"><%= adoptable_pokemon.age %></td>
      </tr>
      <tr>
        <th class="text-end text-zinc-200 font-semibold pr-3">Size</th>
        <td class="font-semibold"><%= adoptable_pokemon.size.capitalize %></td>
      </tr>
      <tr>
        <th class="text-end text-zinc-200 font-semibold pr-3">Temperament</th>
        <td class="font-semibold"><%= adoptable_pokemon.temperament.capitalize %></td>
      </tr>
      <tr>
        <th class="text-end text-zinc-200 font-semibold pr-3">Health Status</th>
        <td class="font-semibold"><%= adoptable_pokemon.health %></td>
      </tr>
    </table>
    <%= image_tag(adoptable_pokemon.species.image, class: "relative col-start-1 row-start-2 lg:h-40 lg:-mr-10 lg:ml-auto", alt: "#{adoptable_pokemon.species.name} pokedex entry") %>
  </article>
<% end %>

app/views/adoptable_pokemons/_adoptable_pokemon_badge.html.erb
<%= link_to adoptable_pokemon_path(adoptable_pokemon[:id]), class: "embla__slide flex-grow-0 flex-shrink-0 basis-auto" do %>
  <div class="bg-accent p-3 rounded-full flex items-center gap-x-4">
    <div class="bg-zinc-100 rounded-full relative h-16 w-16">
      <%= image_tag(adoptable_pokemon.species.image, class: "absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-20 max-w-none") %>
    </div>
    <section class="flex flex-col justify-center text-zinc-200 mr-8">
      <header class="text-xs"><%= adoptable_pokemon.species[:name] %></header>
      <main class="text-lg font-semibold leading-tight text-zinc-100"><%= adoptable_pokemon[:name] %></main>
      <footer class="text-xs"><%= adoptable_pokemon.shelter[:name] %></footer>
    </section>
    <%= image_tag("chevron-right.svg", class: "ml-auto h-8") %>
  </div>
<% end %>

app/views/adoptable_pokemons/_adoptable_pokemons.html.erb
<%= turbo_frame_tag "search_frame" do %>
  <ul class="flex flex-col gap-y-8 mb-8">
    <% @adoptable_pokemons.each do |adoptable_pokemon| %>
      <li>
        <%= render adoptable_pokemon %>
      </li>
    <% end %>
  </ul>
  <% if @adoptable_pokemons.next_page %>
    <%= turbo_frame_tag "search_frame", loading: :lazy, src: adoptable_pokemons_path(@adoptable_pokemon, page: @adoptable_pokemons.next_page, q: params[:q]) do %>
      <ul class="flex flex-col gap-y-8">
        <% 8.times do %>
          <li class="h-36 rounded-2xl bg-orange-200 animate-pulse"></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
<% end %>

app/views/adoptable_pokemons/index.html.erb
<%= render "shared/subpage_banner", image: "adoptable_pokemons/ash.webp", title: "Pokémon For Adoption", description: "Discover and Adopt Your Ideal Pokémon Companion: Explore Profiles, Traits, and Histories to Find the Perfect Match for Your Home and Heart!" do %>
  <%= render "shared/search_input", placeholder: "Search...", data: { controller: "search-frame", action: "search-frame#change" } %>
<% end %>
<section>
  <h2 class="text-2xl font-semibold mb-10">PokéFriends <%= turbo_frame_tag "search_count_frame" do %>(<%= @adoptable_pokemons.count %>) <% end %></h2>
  <%= render "adoptable_pokemons" %>
</section>

app/views/adoptable_pokemons/show.html.erb
<%= render "pokemons/pokemon_banner", pokemon: @adoptable_pokemon.species, adoptable_pokemon: @adoptable_pokemon %>
<section>
  <h3 class="text-2xl font-semibold">Pokémon Information</h3>
  <p class="mt-4">Get to know me better! Here you'll find details about my age, size, temperament, health status, background, and compatibility to help you decide if I'm the perfect match for your home.</p>
  <table class="border-separate border-spacing-x-8 -ml-8 mt-9">
    <tr>
      <th class="font-normal text-zinc-500 text-start align-top">Age</th>
      <td class="font-semibold text-accent"><%= @adoptable_pokemon.age %></td>
    </tr>
    <tr>
      <th class="font-normal text-zinc-500 text-start align-top">Size</th>
      <td class="font-semibold text-accent"><%= @adoptable_pokemon.size.capitalize %></td>
    </tr>
    <tr>
      <th class="font-normal text-zinc-500 text-start align-top">Temperament</th>
      <td class="font-semibold text-accent"><%= @adoptable_pokemon.temperament.capitalize %></td>
    </tr>
    <tr>
      <th class="font-normal text-zinc-500 text-start align-top">Health Status</th>
      <td class="font-semibold text-accent"><%= @adoptable_pokemon.health %></td>
    </tr>
    <tr>
      <th class="font-normal text-zinc-500 text-start align-top">Background</th>
      <td class="font-semibold text-accent"><%= @adoptable_pokemon.background %></td>
    </tr>
    <tr>
      <th class="font-normal text-zinc-500 text-start align-top">Compatibility</th>
      <td class="font-semibold text-accent"><%= @adoptable_pokemon.compatibility %></td>
    </tr>
  </table>
</section>
<section>
  <h3 class="text-2xl font-semibold">My Location</h3>
  <p class="mt-4">Currently, I live in <span class="text-accent font-semibold"><%= @adoptable_pokemon.shelter.name %></span>. This is where you can come to meet me and take me to my new home.</p>
  <%= image_tag("map.webp", class: "w-full object-contain mt-10", alt: "Pokemon map") %>
</section>
<section class="flex flex-col">
  <h3 class="text-2xl font-semibold">Adopting Process</h3>
  <ul class="mt-10 flex flex-col gap-y-6">
    <li class="flex items-center gap-x-4">
      <%= image_tag("form.svg", class: "w-12", alt: "Form icon") %>
      Fill out our online adoption application form.</li>
    <li class="flex items-center gap-x-4">
      <%= image_tag("interview.svg", class: "w-12", alt: "Interview icon") %>
      Participate in a brief interview and home check.</li>
    <li class="flex items-center gap-x-4">
      <%= image_tag("pick-up-truck.svg", class: "w-12", alt: "Pick up truck icon") %>
      Schedule a time to pick up your new Pokémon and receive care instructions.</li>
  </ul>
  <%= render "shared/button_link", text: "Adopt #{@adoptable_pokemon.name}", icon: 'pokeball.svg', href: adopt_adoptable_pokemon_path(@adoptable_pokemon), classname: "w-fit !font-normal self-center mt-12 lg:mt-16 #{'pointer-events-none bg-zinc-400' if @adoptable_pokemon.is_during_adoption}" %>
  <% if @adoptable_pokemon.is_during_adoption %>
    <p class="self-center mt-4 text-accent font-semibold">
      This pokemon is currently during adoption.
    </p>
  <% end %>
</section>

app/views/adoptions/_form.html.erb
<%= form_with model: @adoption, url: adopt_adoptable_pokemon_path(params[:id]) do |form| %>
  <%= form.hidden_field :adoptable_pokemon_id, value: params[:id] %>
  <h3 class="text-xl font-semibold mb-6">Personal Information</h3>
  <%= render "shared/field", form: form, model: @adoption, name: :full_name do  %>
    <%= form.text_field :full_name %>
  <% end %>
  <%= render "shared/field", form: form, model: @adoption, name: :email_address do  %>
    <%= form.email_field :email_address %>
  <% end %>
  <%= render "shared/field", form: form, model: @adoption, name: :phone_number do  %>
    <%= form.telephone_field :phone_number %>
  <% end %>
  <%= render "shared/field", form: form, model: @adoption, name: :city do  %>
    <%= form.select :city, options_for_select(Adoption.cities.map {|k, v| [k.humanize.capitalize, v]}) %>
  <% end %>
  <h3 class="text-xl font-semibold mb-6 mt-14">Household Information</h3>
  <%= render "shared/field", form: form, model: @adoption, name: :household_ownership, custom_label: 'Have You Owned a Pokémon or Pet Before? (Yes/No)' do  %>
    <%= form.select :household_ownership, options_for_select(Adoption.household_ownerships.map {|k, v| [k.humanize.capitalize, v]}) %>
  <% end %>
  <%= render "shared/field", form: form, model: @adoption, name: :household_size, custom_label: 'Number of People in Household' do  %>
    <%= form.number_field :household_size, min: 1 %>
  <% end %>
  <%= render "shared/field", form: form, model: @adoption, name: :household_children, custom_label: 'Any Children? (Yes/No, If Yes, Ages)' do  %>
    <%= form.text_field :household_children %>
  <% end %>
  <h3 class="text-xl font-semibold mb-6 mt-14">Experience and Lifestyle</h3>
  <%= render "shared/field", form: form, model: @adoption, name: :has_experience, custom_label: 'Have You Owned a Pokémon or Pet Before? (Yes/No)' do  %>
    <%= form.select :has_experience, options_for_select([['Yes', true], ['No', false]]) %>
  <% end %>
  <%= render "shared/field", form: form, model: @adoption, name: :why_adopt_pokemon, custom_label: 'Why Do You Want to Adopt a Pokémon?' do  %>
    <%= form.text_area :why_adopt_pokemon %>
  <% end %>
  <%= render "shared/field", form: form, model: @adoption, name: :desired_pokemon_traits, custom_label: 'What Traits Are You Looking for in a Pokémon?' do  %>
    <%= form.text_area :desired_pokemon_traits %>
  <% end %>
  <p class="text-accent font-bold mt-10">
    By clicking the button below,
    I certify that the information provided in this application is true
    and accurate to the best of my knowledge.
    I understand that completing this application does not guarantee the adoption of a Pokémon.
  </p>
  <%= form.submit "Send Application Form" %>
<% end %>

app/views/adoptions/new.html.erb
<%= render "pokemons/pokemon_banner", pokemon: @adoptable_pokemon.species, adoptable_pokemon: @adoptable_pokemon %>
<section>
  <h2 class="text-2xl font-semibold">Adopt a Pokémon: Application Form</h2>
  <p class="mt-4">Complete the form below to start your Pokémon adoption journey. Your responses will help us ensure a good match and provide the best possible care for our Pokémon.</p>
</section>
<%= render "form" %>

app/views/adoptions/success.html.erb
<%= render "pokemons/pokemon_banner", pokemon: @adoptable_pokemon.species, adoptable_pokemon: @adoptable_pokemon %>
<section class="flex flex-col">
  <h2 class="text-2xl font-semibold">Thank You for Your Application!</h2>
  <section class="mt-4 flex flex-col gap-y-6">
    <p>
      Your Pokémon adoption application has been successfully submitted to the PokeFriends team.
      <span class="font-semibold">We will review your application and get back to you within 24 hours.</span>
    </p>
    <p>If you have any questions or need further assistance, please don't hesitate to contact us at 
      <%= mail_to "support@pokefriends.com", class: "text-accent" %>.</p>
    <p class="font-semibold">Thank you for choosing to give a Pokémon a loving home!</p>
  </section>
  <%= image_tag("brand.png", class: "h-20 mt-20 mx-auto") %>
</section>

app/views/evolutions/_evolution.html.erb
<li class="flex flex-col items-center font-semibold text-sm text-accent">
  <%= link_to image_tag(pokemon.image, class: "h-32 object-contain", alt: "#{@pokemon.name} pokedex entry"), pokemon %>
  <%= link_to pokemon.name, pokemon %>
</li>
<% if pokemon.evolution %>
  <li class="flex flex-col items-center gap-y-2 font-semibold text-sm text-accent text-center">
    <%= image_tag("arrow-right.svg", class: "w-6 rotate-90 lg:rotate-0", alt: "#{@pokemon.name} pokedex entry") %>
    <%= "(Level #{pokemon.evolution.level})" if pokemon.evolution.level %>
    <% if pokemon.evolution.item %>
      <div class="flex items-center">
        (
        <%= image_tag(pokemon.evolution.item.image, class: "h-8 object-contain mr-1", alt: "#{@pokemon.name} pokedex entry") %>
        <%= pokemon.evolution.item.name %>
        )
      </div>
    <% end %>
    <%= "(Trade)" if pokemon.evolution.by_trade %>
  </li>
<% end %>

app/views/evolutions/_evolutions.html.erb
<% if @evolutions.length.positive? %>
  <section class="-mt-4">
    <h3 class="text-2xl font-semibold">Evolution Chart</h3>
    <ul class="flex flex-col lg:flex-row items-center justify-center gap-y-4 gap-x-16 w-full lg:mt-8">
      <% @evolutions.each_with_index do |evolution, index| %>
        <%= render "evolutions/evolution", pokemon: evolution.pokemon if index === 0 %>
        <%= render "evolutions/evolution", pokemon: evolution.evolution_pokemon %>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/faq/_question_and_answer.html.erb
<li class="flex flex-col gap-y-2">
  <h2 class="font-semibold text-accent text-xl"><%= question %></h2>
  <p>
    <%= yield %>
  </p>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokefriends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-orange-100 text-zinc-700">
    <main class="container mx-auto pt-8 pb-12 lg:pb-24 px-5 flex flex-col gap-y-12 lg:gap-y-20">
      <%= render "shared/menu" %>
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/main/_achievements.html.erb
<%
  @achievements = [
    {total: '10', label: 'Pokémon Shelters'},
    {total: '60k+', label: 'Pokémon Adopted'},
    {total: '151', label: 'Pokémon Available'},
    {total: '300k+', label: 'Rescued Pokémon'},
  ]
%>
<section class="grid grid-cols-2 gap-y-12 lg:flex lg:justify-between">
  <% @achievements.each do |achievement| %>
    <article class="flex flex-col items-center lg:items-start">
      <h2 class="text-4xl lg:text-6xl text-accent font-semibold"><%= achievement[:total] %></h2>
      <p class="text-sm lg:text-lg"><%= achievement[:label] %></p>
    </article>
  <% end %>
</section>

app/views/main/_banner.html.erb
<header class="flex flex-col lg:flex-row gap-x-8 min-h-96 -mt-4">
  <section class="flex flex-col items-center lg:items-start text-center lg:text-start gap-y-3 self-center w-full lg:w-fit">
    <h1 class="text-6xl font-normal max-w-96 lg:leading-tight">Adopt a <span class="text-accent font-semibold">new</span>
      best friend!</h1>
    <p class="text-xl max-w-80 lg:max-w-96 mt-3 lg:mt-0 lg:pr-20 leading-relaxed">Countless Pokémon are in need of a home. With us, you can
      give them a loving family.</p>
    <%= render "shared/button_link", text: "Find Your Pokémon", icon: 'pokeball.svg', href: adoptable_pokemons_path, classname: "w-fit font-normal text-lg mt-5" %>
  </section>
  <aside class="flex-grow grid lg:grid-cols-[1fr_auto] gap-y-6 mt-8 lg:m-0">
    <%= image_tag("main/banner-eevee.webp", class: "rounded-3xl max-h-44 object-cover w-full", alt: "Eevee painted in Van Gogh style") %>
    <h2 class="text-3xl text-center self-center px-12 w-full hidden lg:block"><span class="text-6xl text-accent font-semibold"><%= @pokemon_count %></span><br />
      Pokémon</h2>
    <%= image_tag("main/banner-psyduck.webp", class: "rounded-3xl col-span-2 object-cover max-h-60 w-full hidden lg:block", alt: "Psyduck splashing in the water at our resort") %>
  </aside>
</header>

app/views/main/_recent_adoptable_pokemons.html.erb
<section>
  <header class="flex items-center justify-between">
    <h3 class="text-2xl font-semibold">Newest Pokémon Friends</h3>
    <%= render "shared/link", text: "View All", href: adoptable_pokemons_path, classname: 'text-end' %>
  </header>
  <ul class="embla overflow-hidden mt-10" id="recentAdoptablePokemon" data-controller="recent-pokemons">
    <li class="embla__container flex gap-x-4">
      <% @recent_adoptable_pokemons.each do |adoptable_pokemon| %>
        <%= render "adoptable_pokemons/adoptable_pokemon_badge", adoptable_pokemon: adoptable_pokemon %>
      <% end %>
    </li>
  </ul>
</section>

app/views/main/index.html.erb
<%= render "banner" %>
<%= render "achievements" %>
<%= render "recent_adoptable_pokemons" %>
<%= render "contact_us" %>

app/views/pokemons/_pokemons.html.erb
<%= turbo_frame_tag "search_frame" do %>
  <ul class="mb-4 grid grid-cols-1 lg:grid-cols-4 justify-between gap-4">
    <% @pokemons.each do |pokemon| %>
      <li>
        <%= render pokemon %>
      </li>
    <% end %>
  </ul>
  <% if @pokemons.next_page %>
    <%= turbo_frame_tag "search_frame", loading: :lazy, src: pokemons_path(@pokemon, page: @pokemons.next_page, q: params[:q]) do %>
      <ul class="grid grid-cols-4 justify-between gap-4">
        <% 8.times do %>
          <li class="h-52 rounded-2xl bg-orange-200 animate-pulse"></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
<% end %>

app/views/pokemons/show.html.erb
<%= render "pokemon_banner", pokemon: @pokemon %>
<%= render "base_stats" %>
<%= render "evolutions/evolutions" %>
<section>
  <header class="flex items-center justify-between mb-10">
    <h3 class="text-2xl font-semibold">Are you interested in adopting <%= @pokemon.name %>?</h3>
    <% if @adoptable_pokemons.length.positive? %>
      <%= render "shared/link", text: "View All", href: adoptable_pokemons_path({ q: @pokemon.name }), classname: 'text-end' %>
    <% end %>
  </header>
  <% if @adoptable_pokemons.length.positive? %>
    <%= render "adoptable_pokemons/adoptable_pokemons" %>
  <% else %>
    <p class="-mt-6">Sorry, there are currently no <%= @pokemon.name %> available for adoption. Please check back later!</p>
  <% end %>
</section>